### Variables
@baseUrl = http://localhost:3000
@userId = 28154b32-d538-464a-b8de-457e4c934d33
@userEmail = dropaccess.net@gmail.com

POST {{baseUrl}}/api/payments/create
Content-Type: application/json

{
  "plan": "individual",
  "userId": "{{userId}}",
  "userEmail": "{{userEmail}}"
}